fail-on-severity: moderate

allow-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - 0BSD
  - CC0-1.0
  - Unlicense

fail-on-scopes:
  - runtime

allow-dependencies-licenses:
  - pkg:npm/some-package@version

comment-summary-in-pr: always

warn-only: false