name: Re-index Codebase

on:
  push:
    branches:
      - main

jobs:
  reindex:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Re-indexing
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_URL }}/api/embed-repo" \
          -H "Content-Type: application/json" \
          -d '{"repository":"otron-io/otron", "force": true}' \
          -H "Authorization: Bearer ${{ secrets.EMBEDDING_API_KEY }}"
